### ISSUE TITLE
Nodejs Pool Config

### ISSUE THREAD

**Issue by CoFix** [scala-network/scala-v7#14]
Hello Dev Team,

Can you share nodejs-pool sigDivisor, denom, maxPaymentTxns, feesForTXN and etc? I cant configure them correctly.

Sample Config: https://raw.githubusercontent.com/ArqTras/nodejs-pool/master/deployment/basestl.sql

Thank You.

**Comment by eeeeLeeee** [comment]
ask about it too. We need the lib about coin and payment.

**Comment by CoFix** [comment]
@stellitecoin We need your help

**Comment by scala-network** [comment]
Please join our discord channel here, https://discord.gg/4adTGc, we have a channel for pool operators, you can ask about setting up pools there.
