### ISSUE TITLE
Please add this link, thank you https://walpool.com/xtl 

### ISSUE THREAD

**Issue by youzidebaba** [scala-network/scala-v7#20]
Please add this link, thank you https://walpool.com/xtl
Please add this link, thank you https://walpool.com/xtl

**Comment by donovansolms** [comment]
Hi,
You pool has been added to the pool list at [stellite.live](https://stellite.live/) as well as in the [GUI miner](https://www.stellite.cash/miner)

Would you mind updating the Masari links on you pool to the Stellite links?
![selection_378](https://user-images.githubusercontent.com/4567303/39800796-5a675ac4-5369-11e8-86de-294f75ea068b.png)

**Comment by prox443** [comment]
@donovansolms Hi, can you add this link too ?
http://xtl.proxpool.com

thks

**Comment by donovansolms** [comment]
@prox443 The pool has been added!

@youzidebaba https://walpool.com/xtl has been hidden because it returns a 404.
