### ISSUE TITLE
Imported the latest .raw, wallet shows 50K remaining

### ISSUE THREAD

**Issue by reppolice** [scala-network/scala-v7#21]
I dont know if it is a bug or a feature, the importer clearlu showed importing 109K blocks. though some weird jump seemed to happen after 55K, starting the wallet gave me 50K remaining, which is now taking hours ago. Could this raw be corrupt somewhere between 55K and 60K, or some other feature?

**Comment by donovansolms** [comment]
Hi,
The .raw file available is up to block 109 766 and we're at block 160 387 right now, about 50 000 blocks behind. I'll make a newer update available as soon as I'm done verifying it.

**Comment by donovansolms** [comment]
GitHub doesn't allow larger than 2GB files, grab this one for now. We are working on a nice tool to simplify this process.

[https://stellite.live/downloads/Stellite-Blockchain-Export-Block-160390.raw](https://stellite.live/downloads/Stellite-Blockchain-Export-Block-160390.raw)
SHA256 for the file is: `e69305c1d504d6ca8d7c3ab96c3d07779338ad252edcc260ec5c5fdd27ca7347`

To import the file, use the following example command
`stellite-blockchain-import --input-file Stellite-Blockchain-Export-Block-160390.raw --verify 0`
