### ISSUE TITLE
rejected shares

### ISSUE THREAD

**Issue by nathjyo** [scala-network/scala-v7#30]
Hi guys 

iv set up a stellite pool as per instructions but when I try to connect I get these issues.

im using hive os and xmr stak for the rig set up. when I connect to the community pool I have no issues with the same settings. not sure what I have done wrong on the pool side.

thanks
![screen shot 2018-08-12 at 8 29 01 pm](https://user-images.githubusercontent.com/37133338/44001250-e316b6be-9e71-11e8-905f-7ae7c400d027.png)

**Comment by ahmyi** [comment]
Im assuming ur using dvandal/cryptonote-nodejs-pool variant should be 3
