### ISSUE TITLE
issue compiling binaries 

### ISSUE THREAD

**Issue by nathjyo** [scala-network/scala-v7#45]
I keep having this error every time I try to compile the binaries

[ 78%] Linking CXX executable unit_tests
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
tests/unit_tests/CMakeFiles/unit_tests.dir/build.make:1544: recipe for target 'tests/unit_tests/unit_tests' failed
make[3]: *** [tests/unit_tests/unit_tests] Error 1
make[3]: Leaving directory '/root/Stellite/build/Linux/master/release'
CMakeFiles/Makefile2:4568: recipe for target 'tests/unit_tests/CMakeFiles/unit_tests.dir/all' failed
make[2]: *** [tests/unit_tests/CMakeFiles/unit_tests.dir/all] Error 2
make[2]: Leaving directory '/root/Stellite/build/Linux/master/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/Stellite/build/Linux/master/release'
Makefile:81: recipe for target 'release-test' failed
make: *** [release-test] Error 2

**Comment by NoreiT** [comment]
Which OS do you try to compile on?

**Comment by nathjyo** [comment]
ubuntu 16

**Comment by nathjyo** [comment]
I wiped and done another install last night woke up to this, 

[ 95%] Linking CXX executable unit_tests
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a(gtest-all.cc.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib/libgtest.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
tests/unit_tests/CMakeFiles/unit_tests.dir/build.make:1544: recipe for target 'tests/unit_tests/unit_tests' failed
make[3]: *** [tests/unit_tests/unit_tests] Error 1
make[3]: Leaving directory '/root/Stellite/build/Linux/master/release'
CMakeFiles/Makefile2:4568: recipe for target 'tests/unit_tests/CMakeFiles/unit_tests.dir/all' failed
make[2]: *** [tests/unit_tests/CMakeFiles/unit_tests.dir/all] Error 2
make[2]: Leaving directory '/root/Stellite/build/Linux/master/release'
Makefile:138: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/root/Stellite/build/Linux/master/release'
Makefile:85: recipe for target 'release-all' failed
make: *** [release-all] Error 2

**Comment by NoreiT** [comment]
I did successfully compiled on Ubuntu 16.04.3 LTS without anything special, just did go for requirements for U17+ and did

git clone --recursive https://github.com/stellitecoin/Stellite
cd Stellite
make

**Comment by nathjyo** [comment]
Thanks I will try again, are there any sap images about?

**Comment by NoreiT** [comment]
not sure what you mean by "sap images"?

**Comment by nathjyo** [comment]
All sorted thanks I forgot to install NVM

also id like to note the resulting build is located here Stellite/build/Linux/master/release/bin

and not Stellite/build/release/bin
