### ISSUE TITLE
New difficulty algorithm

### ISSUE THREAD

**Issue by zawy12** [scala-network/scala-v7#6]
Someone recommended that I suggest [my difficulty algorithm](https://github.com/zawy12/difficulty-algorithms/issues/3) to this coin because of your oscillations.

**Comment by scala-network** [comment]
Implemented the algorithm with the latest release, thank you for you hard work :)

**Comment by zawy12** [comment]
Hi, thanks for letting me.  Did you copy Masari's code?

**Comment by scala-network** [comment]
Yes we've implemented Masari's code
