### ISSUE TITLE
Raspberry Pi 4 (4gb) make release error file missing emmintrin.h 

### ISSUE THREAD

**Issue by AnimusXCASH** [scala-network/scala-v7#64]
`/home/pi/Desktop/Scala/external/defyx/src/blake2/yescrypt-simd.c:37:10: fatal error: emmintrin.h: No such file or directory
 #include <emmintrin.h>
          ^~~~~~~~~~~~~
compilation terminated.
make[3]: *** [external/defyx/CMakeFiles/defyx.dir/build.make:479: external/defyx/CMakeFiles/defyx.dir/src/blake2/yescrypt-simd.c.o] Error 1
make[3]: Leaving directory '/home/pi/Desktop/Scala/build/release'
make[2]: *** [CMakeFiles/Makefile2:413: external/defyx/CMakeFiles/defyx.dir/all] Error 2
make[2]: Leaving directory '/home/pi/Desktop/Scala/build/release'
make[1]: *** [Makefile:141: all] Error 2
make[1]: Leaving directory '/home/pi/Desktop/Scala/build/release'
make: *** [Makefile:87: release] Error 2
`

**Comment by SilentSeir** [comment]
I was unable to resolve this when i attempted to compile on my pi 4 (4gb). 
I would recommend building on amd or intel 64 bit for now.
