### ISSUE TITLE
Not seeing my mined blocks showing up in the wallet

### ISSUE THREAD

**Issue by ns1000** [scala-network/scala-v7#7]
I am not seeing my mined blocks showing up in the wallet. I verified on the (official) block chain explorer that the mined blocks are mine, but nothing in the wallet. I rescanned the full blockchain a few times.

**Comment by ns1000** [comment]
I am using the latest the latest build: Stellite v1.2.1.0 'Chromium v2'

**Comment by BKdilse** [comment]
I'm seeing this too, confirmed I can see the transactions on block explorer, but wallet empty.

**Comment by ns1000** [comment]
I managed to fix it by:
1) Download the latest version (v3)
2) Resync the blockchain
3) Regenerate the wallet file using the keys

**Comment by BKdilse** [comment]
Thanks for that, i'll give it a go.  Thing is, I'm synching with my pool server, which is on 1.2.1.0, and I only built it yesterday.  I'll have to update that 1st, at it was a pain the 1st time.

**Comment by BKdilse** [comment]
Just finished refreshing with old daemon, and balance is there now... 👍 
Will update pool daemon later on.

**Comment by vird** [comment]
Same issue.
Block explorer show that blocks are mine.
Monero 'Chromium v3' (v1.2.2.1-release)
rescan_bc didn't get anything. Recover electrum seed on another machine didn't get anything.

**Comment by vird** [comment]
Just a note. I didn't see my balance at all. Even from mining pool. Block explorer shows that all is ok.

**Comment by scala-network** [comment]
This is most likely the zero balance issue caused by the simple wallet, it's patched in Carbon V2.
