### ISSUE TITLE
Building for Arm8

### ISSUE THREAD

**Issue by neo4uo** [scala-network/scala-v7#71]
Trying to cross compile by using the command:
make depends target=aarch64-linux-gnu

Error:
cd contrib/depends && make HOST=aarch64-linux-gnu && cd ../.. && mkdir -p build/aarch64-linux-gnu/release
make[1]: Entering directory '/home/mcadoryfire/scala/contrib/depends'
Checksum missing or mismatched for native_ccache source. Forcing re-download.
Fetching ccache-3.3.4.tar.bz2 from https://samba.org/ftp/ccache
/bin/sh: 1: curl: not found
Fetching ccache-3.3.4.tar.bz2 from https://bitcoincore.org/depends-sources
/bin/sh: 1: curl: not found
make[1]: *** [funcs.mk:262: /home/mcadoryfire/scala/contrib/depends/sources/download-stamps/.stamp_fetched-native_ccache-ccache-3.3.4.tar.bz2.hash] Error 127
make[1]: Leaving directory '/home/mcadoryfire/scala/contrib/depends'
make: *** [Makefile:51: depends] Error `2

**Comment by Teredic** [comment]
curl isn't installed in your system. I am compiling this build right now and there are another dependency missing, it's gperf.

So you can do this to fix this problem : apt install curl gperf
