### ISSUE TITLE
dyld: Symbol not found

### ISSUE THREAD

**Issue by tobiashaas** [scala-network/scala-v7#74]
I can't get the software to work on my Mac... (MacOS 10.15.6)
I installed it with "Brew" and the Brewfile.

`2020-08-23 23:16:35.386	I Scala 'Panthera' (v4.0.0.0-64f35d8a4)
2020-08-23 23:16:35.386	I Initializing cryptonote protocol...
2020-08-23 23:16:35.386	I Cryptonote protocol initialized OK
2020-08-23 23:16:35.387	I Initializing core...
dyld: lazy symbol binding failed: Symbol not found: __ZN5boost16re_detail_10720027cpp_regex_traits_char_layerIcE4initEv
  Referenced from: /Users/user/Desktop/Scala/bin/scalad
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib

dyld: Symbol not found: __ZN5boost16re_detail_10720027cpp_regex_traits_char_layerIcE4initEv
  Referenced from: /Users/user/Desktop/Scala/bin/scalad
  Expected in: /usr/local/opt/boost/lib/libboost_regex-mt.dylib

zsh: abort      /Users/user/Desktop/Scala/bin/scalad`

**Comment by ahmyi** [comment]
Can you post boost version

**Comment by tobiashaas** [comment]
boost 1.73.0
