### ISSUE TITLE
Wallet shows 0 balance, 0 transactions. Blockchain explorer shows more.

### ISSUE THREAD

**Issue by vird** [scala-network/scala-v7#9]
There is no difference I mine to pool or solimine.
I can provide my address and private view key to developer in some private channel (e.g. tox).

**Comment by scala-network** [comment]
You need to restore your wallet via the seed that was given when the wallet was created.

To do so, create a .bat file and place following commands in it:
for linux: ./stellite-wallet-cli --restore-deterministic-wallet
for win: stellite-wallet-cli.exe --restore-deterministic-wallet
save and start the .bat file.

It will ask you to name your restored wallet, set a new password and type in the seed.

When launching simple wallet afterward, it will receive blocks and your balance will be shown.

**Comment by vird** [comment]
It works for me.

**Comment by AYIK11** [comment]
Hi please am mining stellite. mining on the pool is good payment is been delivered. but i want to check my balance but i dont know how it is done please can someone help me here. am new to this and it getting me sick if am westing much time so please. am using stelliteGUIminer and it working so good. how can l check my balance. THANK YOU ALL

**Comment by AYIK11** [comment]
pool is xtlpool.com:3333
sorry
